package com.boe.simulator.server.matching;

import com.boe.simulator.api.websocket.WebSocketService;
import com.boe.simulator.protocol.types.OrdType;
import com.boe.simulator.protocol.types.PreventMatch;
import com.boe.simulator.protocol.types.Side;
import com.boe.simulator.protocol.types.TimeInForce;
import com.boe.simulator.server.order.Order;
import com.boe.simulator.server.order.OrderRepository;

import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MatchingEngine {
    private static final Logger LOGGER = Logger.getLogger(MatchingEngine.class.getName());

    // Order Reason Codes (p.213) and RestatementReason (p.126)
    public static final byte CANCEL_NO_LIQUIDITY = (byte) 'N';
    public static final byte CANCEL_WOULD_WASH = (byte) 'V';
    public static final byte RESTATED_WASH = (byte) 'W';

    private final Map<String, OrderBook> orderBooks;
    private final Map<String, Object> symbolLocks;
    private final OrderRepository orderRepository;
    private final TradeRepository tradeRepository;
    private final AtomicLong tradeIdGenerator;
    private final List<MatchingEventListener> eventListeners;
    private final boolean allowSelfTrade;
    private final AtomicLong totalMatches;
    private final AtomicLong totalTradeVolume;
    private WebSocketService webSocketService;

    public MatchingEngine(OrderRepository orderRepository, TradeRepository tradeRepository) {
        this(orderRepository, tradeRepository, false);
    }

    public MatchingEngine(OrderRepository orderRepository, TradeRepository tradeRepository, boolean allowSelfTrade) {
        this.orderBooks = new ConcurrentHashMap<>();
        this.symbolLocks = new ConcurrentHashMap<>();
        this.orderRepository = orderRepository;
        this.tradeRepository = tradeRepository;
        this.tradeIdGenerator = new AtomicLong(1000000);
        this.eventListeners = new ArrayList<>();
        this.allowSelfTrade = allowSelfTrade;
        this.totalMatches = new AtomicLong(0);
        this.totalTradeVolume = new AtomicLong(0);

        LOGGER.info("MatchingEngine initialized (Self-trade: " + allowSelfTrade + ")");
    }

    public void setWebSocketService(WebSocketService webSocketService) {
        this.webSocketService = webSocketService;
    }

    public List<Trade> processOrder(Order order) {
        String symbol = order.getSymbol();
        Object symbolLock = symbolLocks.computeIfAbsent(symbol, k -> new Object());

        synchronized (symbolLock) {
        OrderBook book = orderBooks.computeIfAbsent(symbol, OrderBook::new);

        List<Trade> trades = new ArrayList<>();
        boolean immediate = order.getTimeInForce().isImmediate() || order.getOrdType() == OrdType.MARKET;

        if (order.getTimeInForce() == TimeInForce.FOK && fillableQuantity(order, book) < order.getLeavesQty()) {
            order.cancel(CANCEL_NO_LIQUIDITY);
            return trades;
        }

        // If it is a market order or can be matched immediately, attempt matching.
        if (canMatch(order, book)) trades = executeMatching(order, book);

        if (immediate && order.getLeavesQty() > 0 && order.getState().isCancellable()) {
            order.cancel(CANCEL_NO_LIQUIDITY);
        } else if (order.getLeavesQty() > 0 && order.isLive()) {
            book.addOrder(order);
            notifyOrderAdded(order, book);

            if (LOGGER.isLoggable(Level.FINE)) {
                LOGGER.log(Level.FINE, "Order added to book: {0} ({1} @ {2})",
                        new Object[]{order.getClOrdID(), order.getLeavesQty(), order.getPrice()});
            }
        }

        return trades;
        } // end synchronized
    }

    /**
     * Modify an order in the book.
     * Sequence: remove at old price → apply delta/update → re-add at new price → try match.
     * Returns trades generated by the new price crossing the book, or empty list if auto-cancelled.
     */
    public List<Trade> modifyOrder(Order order, String newClOrdID, BigDecimal newPrice,
                                   com.boe.simulator.protocol.types.OrdType newOrdType,
                                   int newOrderQty) {
        String symbol = order.getSymbol();
        Object symbolLock = symbolLocks.computeIfAbsent(symbol, k -> new Object());

        synchronized (symbolLock) {
            OrderBook book = orderBooks.computeIfAbsent(symbol, OrderBook::new);

            // Delta logic (p.77): newLeavesQty = leavesQty + (newOrderQty - currentEffectiveOrderQty)
            int currentQty = order.getEffectiveOrderQty();
            int delta       = newOrderQty - currentQty;
            int newLeavesQty = order.getLeavesQty() + delta;

            boolean samePrice = newPrice == null || order.getPrice() == null || newPrice.compareTo(order.getPrice()) == 0;
            boolean sameOrdType = newOrdType == null || newOrdType == order.getOrdType();
            if (delta < 0 && newLeavesQty > 0 && samePrice && sameOrdType) {
                book.updateInPlace(order, () -> order.modify(newClOrdID, newPrice, newOrdType, newOrderQty, newLeavesQty));
                return List.of();
            }

            // Remove at the current price — must happen BEFORE updating the price on the order
            book.removeOrder(order);
            notifyOrderRemoved(order, book);

            if (newLeavesQty <= 0) {
                // Spec: if resulting leavesQty <= 0, cancel the order
                order.cancel();
                LOGGER.log(Level.INFO, "Modify auto-cancelled order {0} (leavesQty would be {1})",
                        new Object[]{order.getClOrdID(), newLeavesQty});
                return List.of();
            }

            // 3. Apply modification to order
            order.modify(newClOrdID, newPrice, newOrdType, newOrderQty, newLeavesQty);

            // 4. Try matching at new price
            List<Trade> trades = new ArrayList<>();
            if (canMatch(order, book)) {
                trades = executeMatching(order, book);
            }

            // 5. Re-add to book if still live
            if (order.getLeavesQty() > 0 && order.isLive()) {
                book.addOrder(order);
                notifyOrderAdded(order, book);
            }

            return trades;
        }
    }

    public boolean cancelOrder(Order order) {
        OrderBook book = orderBooks.get(order.getSymbol());
        if (book == null) return false;

        boolean removed = book.removeOrder(order);
        if (removed) {
            notifyOrderRemoved(order, book);
            LOGGER.log(Level.FINE, "Order cancelled from book: {0}", order.getClOrdID());
        }

        return removed;
    }

    private boolean canMatch(Order incomingOrder, OrderBook book) {
        if (incomingOrder.getOrdType() == OrdType.MARKET) return true;

        BigDecimal incomingPrice = incomingOrder.getPrice();
        if (incomingPrice == null) return false;

        if (incomingOrder.getSide() == Side.BUY) {
            BigDecimal bestAsk = book.getBestAsk();
            return bestAsk != null && incomingPrice.compareTo(bestAsk) >= 0;
        } else { // Sell
            BigDecimal bestBid = book.getBestBid();
            return bestBid != null && incomingPrice.compareTo(bestBid) <= 0;
        }
    }

    private int fillableQuantity(Order order, OrderBook book) {
        int needed = order.getLeavesQty();
        int available = 0;
        for (Order resting : book.getOppositeOrders(order.getSide())) {
            if (!isPriceAcceptable(order, resting.getPrice())) break;
            if (!resting.getState().isActive()) continue;
            PreventMatch prevention = preventionBetween(order, resting);
            if (prevention != null) {
                if (prevention.modifier() == PreventMatch.CANCEL_OLDEST) continue;
                break;
            }
            available += resting.getLeavesQty();
            if (available >= needed) break;
        }
        return available;
    }

    private static boolean isPriceAcceptable(Order incoming, BigDecimal restingPrice) {
        if (incoming.getOrdType() == OrdType.MARKET) return true;
        if (incoming.getPrice() == null) return false;
        int cmp = incoming.getPrice().compareTo(restingPrice);
        return incoming.getSide() == Side.BUY ? cmp >= 0 : cmp <= 0;
    }

    private List<Trade> executeMatching(Order aggressiveOrder, OrderBook book) {
        List<Trade> trades = new ArrayList<>();

        while (aggressiveOrder.getLeavesQty() > 0 && canMatch(aggressiveOrder, book)) {
            List<Order> passiveOrders = aggressiveOrder.getSide() == Side.BUY ? book.getTopAskOrders() : book.getTopBidOrders();

            if (passiveOrders.isEmpty()) break;

            // FIFO: take the first order from the level
            Order passiveOrder = passiveOrders.get(0);

            // Stale terminal order still in book (race between fill and book removal)
            if (!passiveOrder.getState().isActive()) {
                book.removeOrder(passiveOrder);
                continue;
            }

            PreventMatch prevention = preventionBetween(aggressiveOrder, passiveOrder);
            if (prevention != null) {
                if (applyPrevention(prevention, aggressiveOrder, passiveOrder, book)) break;
                continue;
            }

            // Calculate quantity to be executed
            int fillQty = Math.min(aggressiveOrder.getLeavesQty(), passiveOrder.getLeavesQty());

            // Execution price is the price of the passive order (price-time priority).
            BigDecimal execPrice = passiveOrder.getPrice();

            // Create trade
            Trade trade = createTrade(aggressiveOrder, passiveOrder, fillQty, execPrice);
            trades.add(trade);

            // Update orders
            aggressiveOrder.fill(fillQty, execPrice);
            passiveOrder.fill(fillQty, execPrice);

            // Update last trade price
            book.setLastTradePrice(execPrice);

            orderRepository.saveAsync(passiveOrder);
            tradeRepository.saveAsync(trade);

            notifyTradeExecuted(trade, book);

            // If the passive order has been completed, remove it from the book.
            if (passiveOrder.getLeavesQty() == 0) book.removeOrder(passiveOrder);

            // Update statistics
            totalMatches.incrementAndGet();
            totalTradeVolume.addAndGet(fillQty);

            LOGGER.log(Level.INFO, "Trade executed: {0} x {1} @ {2}", new Object[]{
                    trade.getSymbol(),
                    fillQty,
                    execPrice
            });
        }

        return trades;
    }

    private PreventMatch effectivePreventMatch(Order order) {
        if (order.getPreventMatch() != null) return order.getPreventMatch();
        return allowSelfTrade ? null : PreventMatch.PORT_DEFAULT;
    }

    // Match Trade Prevention (PreventMatch, p.207): the inbound order's instruction applies
    private PreventMatch preventionBetween(Order inbound, Order resting) {
        PreventMatch in = effectivePreventMatch(inbound);
        PreventMatch rest = effectivePreventMatch(resting);
        if (in == null || rest == null || in.level() != rest.level()) return null;
        if (inbound.getUsername() == null || !inbound.getUsername().equals(resting.getUsername())) return null;
        if (in.level() == PreventMatch.EFID_LEVEL && !Objects.equals(inbound.getClearingFirm(), resting.getClearingFirm())) return null;
        if (in.tradingGroup() != 0 && rest.tradingGroup() != 0 && in.tradingGroup() != rest.tradingGroup()) return null;
        return in;
    }

    // true when the inbound order is cancelled and matching must stop
    private boolean applyPrevention(PreventMatch prevention, Order inbound, Order resting, OrderBook book) {
        int inQty = inbound.getLeavesQty();
        int restQty = resting.getLeavesQty();
        boolean cancelInbound = false, cancelResting = false;
        int decrementInbound = 0, decrementResting = 0;

        switch (prevention.modifier()) {
            case PreventMatch.CANCEL_NEWEST -> cancelInbound = true;
            case PreventMatch.CANCEL_OLDEST -> cancelResting = true;
            case PreventMatch.CANCEL_SMALLEST -> {
                cancelInbound = inQty <= restQty;
                cancelResting = restQty <= inQty;
            }
            case PreventMatch.DECREMENT, PreventMatch.DECREMENT_LEAVES_ONLY -> {
                PreventMatch restingPrevention = effectivePreventMatch(resting);
                if (inQty == restQty || (restQty > inQty && !restingPrevention.decrements())) {
                    cancelInbound = cancelResting = true;
                } else if (inQty < restQty) {
                    cancelInbound = true;
                    decrementResting = inQty;
                } else {
                    cancelResting = true;
                    decrementInbound = restQty;
                }
            }
            default -> cancelInbound = cancelResting = true;
        }
        LOGGER.log(Level.INFO, "Match trade prevention {0}: inbound {1}, resting {2}",
                new Object[]{prevention.modifier(), inbound.getClOrdID(), resting.getClOrdID()});

        boolean orderQtyToo = prevention.modifier() == PreventMatch.DECREMENT;
        if (cancelResting) {
            book.removeOrder(resting);
            resting.cancel(CANCEL_WOULD_WASH);
            orderRepository.saveAsync(resting);
            notifyOrderCancelled(resting, CANCEL_WOULD_WASH, book);
        }
        if (decrementResting > 0) {
            int qty = decrementResting;
            book.updateInPlace(resting, () -> resting.decrement(qty, orderQtyToo));
            orderRepository.saveAsync(resting);
            notifyOrderRestated(resting, false, book);
        }
        if (decrementInbound > 0) {
            inbound.decrement(decrementInbound, orderQtyToo);
            notifyOrderRestated(inbound, true, book);
        }
        if (cancelInbound) inbound.cancel(CANCEL_WOULD_WASH);
        return cancelInbound;
    }

    private Trade createTrade(Order aggressive, Order passive, int qty, BigDecimal price) {
        long tradeId = tradeIdGenerator.getAndIncrement();

        boolean aggressiveIsBuy = aggressive.getSide() == Side.BUY;

        return Trade.builder()
                .tradeId(tradeId)
                .symbol(aggressive.getSymbol())
                .buyOrderId(aggressiveIsBuy ? aggressive.getOrderID() : passive.getOrderID())
                .buyClOrdID(aggressiveIsBuy ? aggressive.getClOrdID() : passive.getClOrdID())
                .buyUsername(aggressiveIsBuy ? aggressive.getUsername() : passive.getUsername())
                .sellOrderId(aggressiveIsBuy ? passive.getOrderID() : aggressive.getOrderID())
                .sellClOrdID(aggressiveIsBuy ? passive.getClOrdID() : aggressive.getClOrdID())
                .sellUsername(aggressiveIsBuy ? passive.getUsername() : aggressive.getUsername())
                .quantity(qty)
                .price(price)
                .matchingUnit(aggressive.getMatchingUnit())
                .clearingFirm(aggressive.getClearingFirm())
                .aggressorSide(aggressive.getSide())
                .build();
    }

    public Optional<OrderBook> getOrderBook(String symbol) {
        return Optional.ofNullable(orderBooks.get(symbol));
    }

    public Set<String> getActiveSymbols() {
        return new HashSet<>(orderBooks.keySet());
    }

    public void addEventListener(MatchingEventListener listener) {
        eventListeners.add(listener);
    }

    public void removeEventListener(MatchingEventListener listener) {
        eventListeners.remove(listener);
    }

    // Methods of notification
    private void notifyTradeExecuted(Trade trade, OrderBook book) {
        for (MatchingEventListener listener : eventListeners) {
            try {
                listener.onTradeExecuted(trade, book);
            } catch (Exception e) {
                LOGGER.log(Level.WARNING, "Error notifying listener", e);
            }
        }
    }

    private void notifyOrderCancelled(Order order, byte reason, OrderBook book) {
        for (MatchingEventListener listener : eventListeners) {
            try {
                listener.onOrderCancelled(order, reason, book);
            } catch (Exception e) {
                LOGGER.log(Level.WARNING, "Error notifying listener", e);
            }
        }
        if (webSocketService != null) webSocketService.broadcastOrderBookUpdate(order.getSymbol(), book, 10);
    }

    private void notifyOrderRestated(Order order, boolean incoming, OrderBook book) {
        for (MatchingEventListener listener : eventListeners) {
            try {
                listener.onOrderRestated(order, RESTATED_WASH, incoming, book);
            } catch (Exception e) {
                LOGGER.log(Level.WARNING, "Error notifying listener", e);
            }
        }
    }

    private void notifyOrderAdded(Order order, OrderBook book) {
        eventListeners.forEach(listener -> listener.onOrderAdded(order, book));

        if (webSocketService != null) webSocketService.broadcastOrderBookUpdate(order.getSymbol(), book, 10);
    }

    private void notifyOrderRemoved(Order order, OrderBook book) {
        eventListeners.forEach(listener -> listener.onOrderRemoved(order, book));

        if (webSocketService != null) webSocketService.broadcastOrderBookUpdate(order.getSymbol(), book, 10);
    }

    // Statistics
    public long getTotalMatches() {
        return totalMatches.get();
    }

    public long getTotalTradeVolume() {
        return totalTradeVolume.get();
    }

    public int getTotalOrdersInBooks() {
        return orderBooks.values().stream()
                .mapToInt(OrderBook::size)
                .sum();
    }

    public void reset() {
        orderBooks.clear();
        totalMatches.set(0);
        totalTradeVolume.set(0);
        LOGGER.info("MatchingEngine reset: all order books cleared");
    }

    public void printStatistics() {
        LOGGER.info("========== Matching Engine Statistics ==========");
        LOGGER.log(Level.INFO, "Active Symbols: {0}", orderBooks.size());
        LOGGER.log(Level.INFO, "Total Orders in Books: {0}", getTotalOrdersInBooks());
        LOGGER.log(Level.INFO, "Total Matches: {0}", totalMatches.get());
        LOGGER.log(Level.INFO, "Total Trade Volume: {0}", totalTradeVolume.get());
        LOGGER.info("===============================================");
    }

    public interface MatchingEventListener {
        default void onTradeExecuted(Trade trade, OrderBook book) {}
        default void onOrderAdded(Order order, OrderBook book) {}
        default void onOrderRemoved(Order order, OrderBook book) {}
        default void onOrderCancelled(Order order, byte reason, OrderBook book) {}
        default void onOrderRestated(Order order, byte reason, boolean incoming, OrderBook book) {}
    }
}